blockstack/blockstack.org

app/docs/docs/cli-basic-usage.md, app/docs/docs/cli-extended-usage.md
Update usage documentation for 0.14.
=> Update usage documentation for 0.14

app/docs/docs/cli-basic-usage.md
cat from here documents to zone file
=> minor fix: echo => cat

app/js/pages/IntroPage.js
changed the reference link for the blockstack card-link from the cli repo to the core repo.
=> Issue #227 Intro Link to Blockstack-Core Repo

app/js/components/Header.js, app/js/components/MobileNav.js, app/js/pages/FAQPage.js, app/styles/main.css, firebase.json
=> Hamburger nav

app/js/components/Footer.js
=> Fixed broken FAQ link

app/js/components/EmbedYouTube.js, app/js/pages/TutorialPage.js, app/styles/main.css
=> Adjust video padding on tutorials item page

CONTRIBUTING.md, README.md
Closes: #116 
This is a second PR to resolve merge conflicts with the contributing guidelines.
This contains all the changes recent to the latest review of the contributing guide found here #330
=> Create Contributing Guide

app/js/components/EmbedYouTube.js, app/styles/main.css
=> Remove constant iframe height

app/styles/main.css
Closes: #387 
This was a quick fix I just switched the footer-logo width in the 768px media query so it retains it size until it disappears.
should be a quick review @guylepage3
=> Footer Logo Size Fix

app/js/components/Article.js, app/js/components/EmbedYouTube.js, app/js/pages/FundingPage.js, app/styles/main.css
=> Update funding page to use EmbedYouTube component

app/js/config.js
=> Update Patrick Stanley’s bio

app/js/pages/CareersPage.js
=> Fix wording of 'Key Values'

app/js/Routes.js, gulp/tasks/configFirebase.js
Redirect to https://community.blockstack.org/developers-getting-started from `blockstack.org/devs/`
=> Redirect from /devs to the community landing page.

gulp/tasks/configFirebase.js
This will redirect `/dev` to the community devs site.
=> Redirect /dev to community devs site as well

firebase.json, gulp/tasks/configFirebase.js
This adds a redirect to a form for submitting simple bug reports, issues with documentation, etc.
=> Add redirect for /bugs

pages/install/install.md
=> Update release links

common/index.js, components/footer/Footer.js, components/fund-app/FundApp.js, components/main-menu/MainMenu.js, components/why-bs/WhyBS.js
App mining is launching soon and we needed to add references throughout the site to it so people can find it!
- Added link and text to 'Why build' section on homepage -> https://github.com/blockstack/blockstack.org/issues/680
- Added link to header and footer -> https://github.com/blockstack/blockstack.org/issues/678
- Added link to fund your dapp section -> https://github.com/blockstack/blockstack.org/issues/679
https://deploy-preview-681--blockstack.netlify.com/
=> App Mining Launch Updates

components/jobs/index.js, pages/legal/privacy-policy/privacy.md
Adds a line to the privacy policy, and fixes an error with listing jobs.
=> Add line to Privacy Policy and fix Jobs listing

pages/_app.js
This adds a hellobar component to capture emails for app mining:
resolves https://github.com/blockstack/blockstack.org/issues/693
=> Add hellobar script

pages/install/install.md
To review, just double check the URLs, I've checked and they should be good.
=> links to v0.35.0 browser

pages/install/install.md
Browser download links updated for 0.35.1.
=> browser download links update

components/footer/Footer.js, components/main-menu/MainMenu.js, components/our-community/OurCommunity.js, components/top-area/TopArea.js, pages/about/about.md, pages/careers/values.md
=> Fix GitHub spelling

common/index.js, components/footer/Footer.js, components/main-menu/MainMenu.js, pages/about/about.md, pages/papers/papers.md, pages/press/featured.js
- Papers page copy change #772
- Link changes on About #773
- Press revision and addition #768
- Add back link to the community site in the footer (also update newsletter archive) #733
=> Additional Misc Edits

pages/_document.js
This PR adds the segment code to the site.
=> Add Segment

pages/technology/index.js
- resolves #973
https://deploy-preview-974--blockstack.netlify.com/technology/
=> Smart contract language

common/markdown/roadmap.md, components/team/data.js
This updates our team with our newest hire, and updates the roadmap.
=> Team + Roadmap

components/newsletter/wrapper.js
Fixes https://github.com/blockstackpbc/devops/issues/168
=> fix: The url for email sign up

components/footer/index.js, components/header/index.js, components/nav-item/index.js, pages/_app.js
This updates and renders the hellobar component we have to give a link to the upcoming blockstack summit.
=> Update Hellobar for summit

pages/press/index.js
=> feat: Add press contact information

pages/papers/index.js
日本人 means Japanese people, not Japanese language
=> fix translation

common/constants.js, common/index.js, common/markdown/privacy.md, components/footer/index.js
See commits for issue references.
=> Miscellaneous updates

pages/technology/index.js
With changes in the structure of the docs, we need to update links.
Docs PR: https://github.com/blockstack/docs.blockstack/pull/542
=> Update tutorial links
